# Generated by Django 6.0.1 on 2026-01-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/%Y/%m/%d', verbose_name='프로필 사진'),
        ),
    ]
