"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_qowc9y3)i!#1)z*w(%zx!ws*zyx2b-9yb81(6@uw&)e7$6k*p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls', #polls app 등록
    'account',
    'django_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"templates",],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', #내가 연결할 DB 엔진(Lib)
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True

#######################################
# 사용자 관리시 사용하는 Usermodel 변경
#######################################
AUTH_USER_MODEL = "account.CustomUser"

###############################
#로그인 하지 않은 사용자가 @login_required View 함수를 호출했을 때 이동할 url
# -> 로그인 페이지로 이동 (/account/login?next=View의 url)
#######################
LOGIN_URL= '/account/login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


###########
#static 파일들을 요청할 때 시작할 url 경로
#
# app/static -> 아래있는 경로의 static 파일 요청 url
## http://ip:port/STATIC_URL/
STATIC_URL = '/static/'

#app/static 디렉토리 이외의 경로에 static 파일들을 넣을 경우 디랙토리를 당룩하오산다
STATICFILES_DIRS=[BASE_DIR/'static']

STATIC_ROOT = BASE_DIR / "static_files"
# python manage.py collectstatic 을 실행
# 모든 static 경로(app/static, STATICFILES_DIRS)의 STATIC파일들을 STATIC_ROOT 디렉토리 아래로 복사한다.
# - 모든 static 파일들을 한 곳으로 모아준다.
# 운영환경(django.pdf 참고)
# 웹서버(HTTP서버)+WSGI/ASGI(쟝고 실행환경)
## WSGI: backend 동적 코드를 실행 (MVT 컴포넌트를 실행)
## 웹서버: 정적 파일을 서비스(html, css, js, img, client 에게 응답)
# collectstatic 명령어로 static 파일들을 한 디렉토리로 모아놓고 web 서버에 그 디렉토리를 설정해 서비스 할 수 있게 한다.

###############
#파일 업로드 설정
#############
MEDIA_URL = "/media/" # 업로드 된 파일 다운로드 요청 url 경로
MEDIA_ROOT = BASE_DIR / "meida" # 업로드 된 파일을 저장할 디렉토리

# ip: port/media/xxxxx -> xxxxx 파일을 MEDIA_ROOT 디렉토리 아래서 찾는다.